export default { 
	  MIDNIGHTBLUE : 'midnightblue',
	  GREEN: '#41a81a',
	  ORANGE: '#974806',
	  LIGHTORANGE: '#FFAF6D',
	  GRAYGREEN: '#b4e1d0',
	  SEAGREEN: '#00c88d',
	  SEAGREENRGBA: "rgba( 0, 200, 141, .5)",
	  LIGHTBLUE: '#50e1dd',
	  DARKPURPLE: '#0e0029',
	  PURPLE: '#4A0837',
	  MAUVE: '#7e172b',
	  LIGHTMAUVE: '#f4838A',
	  LIGHTERMAUVE: '#FFBABF',
	  BLUE: '#1575c8',
	  LIGHTGRAY: '#777',
	  GERM :'germ',
	  GERMS: 'germs',
	  LEUKS: 'leuks',
	  BUBBLE :'bubble',
	  BUBBLEPRESS: 'bubblePress',
	  LEUK : 'leuk',
	  DESTCONTROL : 'destControl',
	  GAMEOVER: 'gameOver',
	  WIN: 'win',
	  LOSE: 'lose',
	  STOP: 'stop',
	  STOPPED: 'stopped',
	  CONTROLS: 'controls',
	  STAGING: 'staging',
	  BUBBLECOUNT: 3,
	  BUBBLER: 25,
	  CONTROLSHEIGHT: 30,
	  STAGINGHEIGHT: 25,
	  GERMR: 4,
	  SIZES:{
	  	0: 6,
	  	1: 12,
	  	2: 18
	  },
	  SCALEFACTORS:{
		0: 1.2,
		1: 1.12,
		2: 1.08
	  },
	  BUBBLESCALEFACTOR: 1.2,
	  MONTHS: { 0: "January", 1: "February", 2: 'March', 3: "April", 4:"May", 5:"June", 6: "July", 7: "August", 8: "September", 9: "October", 10: "November", 11: "December" },
	  DAYS: { 0: "Sunday", 1: "Monday", 2: "Tuesday", 3: "Wednesday", 4: "Thursday", 5: "Friday", 6: "Saturday" },
	  tAlert: function( val, freq ){
	  	if( Math.random() < freq ) alert( val );
	  }
}
